generator:
  class: sfPropelGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              JobeetJob
    plural:                JobeetJobs
    route_prefix:          jobeet_job
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        is_activated: { label: Activated?, help: Wheter the user has activated the job, or not}
        is_public: { label: Public?, help: Whether the job can also be published on affiliate website or not} 
      list:
        peer_method: doSelectJoinJobeetCategory
        actions:
            deleteNeverActivated: {label: Delete never activated jobs}
        object_actions:
            extend: ~
            _edit: ~
            _delete: ~ 
        batch_actions: 
            _delete: ~
            extend: ~
        sort: [expires_at, desc] 
        max_per_page: 10   
        title: Job management
        display: [company, position, location, url, is_activated, email]
        layout: stacked
        params: |
          %%is_activated%% <small>%%jobeet_category%%</small> - %%company%%
          (<em>%%email%%</em>) is looking for a %%=position%% (%%location%%)
      filter:
          display: [category_id, company, position, description, is_activated, is_public, email, expires_at]
      form:
          class: BackendJobeetJobForm
          display:
               Content: [category_id, type, company, logo, url, position, location, description, how_to_apply, is_public, email]
               Admin:   [_generated_token, is_activated, expires_at]
      edit:    
        title: Editing Job "%%company%% is looking for a %%position%%"
      new:
        title: Job creation
