<?php


/**
 * Skeleton subclass for representing a row from the 'jobeet_job' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat May  7 21:01:10 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetJob extends BaseJobeetJob {

	/**
	 * Initializes internal state of JobeetJob object.
	 * @see        parent::__construct()
	 */
	
	
	public function save (PropelPDO $con =null)
	{
		if ($this->isNew() && !$this->getExpiresAt())
		{
			$now = $this->getCreatedAt() ? $this->getCreatedAt('U') : time();
			$this->setExpiresAt($now + 86400 * sfConfig::get('app_active_days'));
		}
		
		if(!$this->getToken())
		{
			$this->setToken(sha1($this->getEmail().rand(11111, 99999)));
		}
		return parent::save($con);
	}
	
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	public function __toString()
	{
		return sprintf('%s at %s (%s)', $this->getPosition(), $this->getCompany(), $this->getLocation());
	}
	
	public function extend($force = false)
	{
		if (!$force && !$this->expireSoon())
		{
			return false;
		}
		
		$this->setExpiresAt(time()+ 86400 * sfConfig::get('app_actives_days'));
		$this->save();
		
		return true;
	}
	
	public function publish()
	{
		$this->setIsActivated(true);
		$this->save();
	}
	

	
	public function getTypeName()
	{
		return $this->getType() ? JobeetJobPeer::$types[$this->getType()] : '';
	}
	
	public function isExpired()
	{
		return $this->getDaysBeforeExpires() < 0;
	}
	
	public function expireSoon()
	{
		return $this->getDaysBeforeExpires() <5;
	}
	
	public function getDaysBeforeExpires()
	{
		return ceil(($this->getExpiresAt('U')-time())/86400);
	}

	
	public function getCompanySlug()
	{
	  return Jobeet::slugify($this->getCompany());
	}

	public function getPositionSlug()
	{
	  return Jobeet::slugify($this->getPosition());
	}

	public function getLocationSlug()
	{
	  return Jobeet::slugify($this->getLocation());
	}

} // JobeetJob
